### ISSUE TITLE
Update installation guidelines

### ISSUE THREAD

**Issue by alexec** [astellato/ofxSyphon#19]
This was very useful to me to get this set-up, maybe reference it?

http://forum.openframeworks.cc/t/an-easier-ofxsyphon/9017/23

**Comment by bangnoise** [comment]
A better solution to this if anyone has the time would be to fix the issues on the OF project generator which affect ofxSyphon

ofZach/projectGeneratorSimple#56
ofZach/projectGeneratorSimple#57
ofZach/projectGeneratorSimple#58
ofZach/projectGeneratorSimple#59
