### ISSUE TITLE
What about the future ?

### ISSUE THREAD

**Issue by martialgallorini** [astellato/ofxSyphon#20]
Hello,

Syphon is really a must have for openFrameworks.
Unfortunately, this addon is quite complicated to use for XCode noobs.

I tried and keep trying but can't get it to work with oF0.8.4

Is there a chance this addons will work properly with projectGenerator one day ?

thanks a lot by the way

**Comment by bangnoise** [comment]
The issues are all with projectGenerator, not ofxSyphon. Try enquiring at https://github.com/ofZach/projectGeneratorSimple
