### ISSUE TITLE
can't get the examples to work

### ISSUE THREAD

**Issue by martialgallorini** [astellato/ofxSyphon#21]
hello,

Thanks for the addon.
I can't get it to work even after following precisely the instructions in the readme file.

I then tried to compile the examples but still have problems.
after setting the project i still have an issue compiling the example : 

..libs/openFrameworks/types/ofTypes.h:9:10: 'tr1/memory' file not found

Using oF 0.8.4 on macosx 10.9.2

**Comment by bangnoise** [comment]
The ServerDirectory example was broken with 0.8.4 (sorry) - I've just pushed a new example. The new ServerDirectory example and the current Basic example both work for me with 0.8.4 on OS X 10.10 - my 10.9 VM is updating right now so I can't check.

If you have errors with the Basic example or my newly pushed example_ServerDirectory, then paste the errors you're getting.

If you can't get it to work with your own project then check you've followed the instructions in the ofxSyphon README.md then paste the errors you get here.

**Comment by martialgallorini** [comment]
Thanks you for your suggestions.
I grabbed the latest example_ServerDirectory. It compiles and run but once i hit space it crashes : 

![1](https://cloud.githubusercontent.com/assets/3931994/7271214/37e831a2-e8e2-11e4-829c-eafff46f1948.png)

As for the SimpleExample : i can't make it build. I followed the instructions in the readme.md (see pics) 

![capture d ecran 2015-04-22 a 11 20 01](https://cloud.githubusercontent.com/assets/3931994/7271253/6b41a6b4-e8e2-11e4-9ded-6e57c07b034a.png)

![capture d ecran 2015-04-22 a 11 22 01](https://cloud.githubusercontent.com/assets/3931994/7271258/705d4342-e8e2-11e4-8039-35b68e497b8a.png)

But i stil end up with the following error : 

![2](https://cloud.githubusercontent.com/assets/3931994/7271275/8f3dd1f0-e8e2-11e4-8c21-42d83d9d3d49.png)

**Comment by martialgallorini** [comment]
i made a clean project. I was able to build it (still impossible to build the previous example)
but this one crashed after loading : 

![capture d ecran 2015-04-22 a 20 38 59](https://cloud.githubusercontent.com/assets/3931994/7282355/c7b5aa9c-e92f-11e4-93ab-b350cc10ee36.png)

**Comment by bangnoise** [comment]
I suspect something was printed to the console which would provide more information. A linked library is unavailable - perhaps you missed the build phase to copy the Syphon framework?

**Comment by bangnoise** [comment]
The example projects should need no changes to build and run. The instructions in the README have already been applied to them.

**Comment by martialgallorini** [comment]
Ok i had my custom app to work. It seems the syphon framework was added twice : once when i added the addon, and one more time when i followed the readme instructions.

by the way i also had to add SyphonNameboundClient.m to the addon source library in my project as it wasn't added automatically.
