### ISSUE TITLE
Getting EXC_BAD_ACCESS on startup.

### ISSUE THREAD

**Issue by mattfelsen** [astellato/ofxSyphon#27]
Hi! I'm seeing this behavior with regularity when quitting & relaunching my app. I'm using OF 0.9.0 and the `OpenFrameworks-0.9` branch of this repo. Looks like `mSyphon` is pointing at *something*...that doesn't exist anymore?

Nothing crazy with Syphon in my app, just an `ofxSyphonServer syphon;` declaration in my header file and a `syphon.publishScreen();` in `draw()` Any thoughts? Thanks!

<img width="548" alt="screen shot 2015-11-29 at 8 14 49 pm" src="https://cloud.githubusercontent.com/assets/2334552/11461684/23f049ee-96d6-11e5-9d30-a03bbb231dca.png">

**Comment by bangnoise** [comment]
Can you provide a simple project which recreates the issue?

**Comment by mattfelsen** [comment]
Hmm...just stripped everything out of the app except the essentials and I'm not seeing this anymore. Guess there's some weird stuff happening on my side after all. Thanks for the suggestion :stuck_out_tongue_closed_eyes:
