### ISSUE TITLE
Server doesn't list clients existing before app start

### ISSUE THREAD

**Issue by mruegenberg** [astellato/ofxSyphon#29]
I'm not sure if this is maybe a known limitation of Syphon itself, but ofxSyphonServerDirectory doesn't seem to list servers that existed before startup.

To reproduce:

1. Start the Simple Server example app from Syphon
2. Start `example-ServerDirectory`
3. The screen remains blank even after pressing a key
4. Close and reopen the Simple Server app
5. The server appears in the (still open) example-ServerDirectory

**Comment by bangnoise** [comment]
Thanks for the reports. This isn't a Syphon limitation. If you have time to take a look, we'd welcome a pull request if you find a solution.
