### ISSUE TITLE
is it possible to change file name + path for syphon recorder?

### ISSUE THREAD

**Issue by stephanschulz** [astellato/ofxSyphon#33]
Is it possible through the addon to change the path where files get saved by the syphon recorder app?

Is it possible to change the file name after calling individualTextureSyphonServer.setName("Texture Output"); in setup?
I would like it to contain custom info for each recording.

Ideally one would also be able to change the resolution settings from OF for the recorded videos.

My app starts and stops multiple recordings automatically using this solution:
https://forum.openframeworks.cc/t/ofxsyphon-start-and-stop-recording/24187

I know this might be not possible but i thought i'd ask.
thanks.

**Comment by bangnoise** [comment]
You can change the server's name, which will affect the file name, using setName().

You can't remotely set other Syphon Recorder settings. Record actions with Automator maybe?
