### ISSUE TITLE
Server produces just diagonal line

### ISSUE THREAD

**Issue by autr** [astellato/ofxSyphon#35]
Hi, I'm finding ofxSyphonServer is producing just a single diagonal line of pixels from the output - this is using both` publishScreen()` and `publishTexture(&fbo.getTexture())`

Screengrab attached 

![screen shot 2017-05-02 at 16 37 57](https://cloud.githubusercontent.com/assets/1035590/25626021/13f77372-2f56-11e7-8345-722e75006e3a.png)

The line of pixels that is there though does seem to be realtime!

**Comment by bangnoise** [comment]
Can you share a simple project to reproduce this?

**Comment by autr** [comment]
I've isolated the problem but it's odd - there is a UI addon that I've made and if drawn anywhere inside the ofApp draw() function this is what causes the Syphon output to become this diagonal line. If I don't bother drawing it then everything works fine.

Only thing I can think is the UI addon uses a lot of FBOs / textures?

**Comment by autr** [comment]
Temporary fix is to toggle the UI on and off with a key, and the initial state is not inactive.

The first time the UI draw function runs it allocates lots of little FBOs for each UI element based on the dimensions passed to it, so I suppose these must be interfering with the texture passed to Syphon?

**Comment by bangnoise** [comment]
Sounds like your addon is not properly restoring GL state. I'm going to close this issue, but reopen it if you discover any problem within ofxSyphon.
