### ISSUE TITLE
Syphon/Syphon.h file not found with open frameworks nightly (20170714)

### ISSUE THREAD

**Issue by ukelady** [astellato/ofxSyphon#38]
Hi! I've been using syphon in my xcode project for a while. I've just swapped to openframework nightly in order to use some specific feature, but now I can't get syphon working anymore. 

I've read [this thread](https://github.com/astellato/ofxSyphon/issues/16), and have checked that I've got Syphone.framework in _Link Library with Binaries_ (see the following screenshot)

![screen shot 2017-10-06 at 17 29 06](https://user-images.githubusercontent.com/1383198/31285935-eb20ab34-aabc-11e7-8bd3-4e39814ed5a0.png)

Has anyone got it working with the latest OF nightly? Am I missing certain configurations?

**Comment by roymacdonald** [comment]
in the build settings add ../../../addons/ofxSyphon/libs/Syphon/lib/osx to the Framework Search Paths

**Comment by bangnoise** [comment]
Did you use the Project Generator to create the Xcode project?

If so, please could you open a bug for the main OpenFrameworks project? Something in the Project Generator has probably changed or broken.

**Comment by roymacdonald** [comment]
@bangnoise Yes, I used PG. Using the current HEAD. Just recompiled it, and the problem persists. Also on OF's current HEAD. 
The only fix is what I mentioned before. 
There is this ADDON_FRAMEWORKS variable in the addons_config.mk file that I can't make work.
I'll open an issue in the PG repo.

**Comment by ThomasLengeling** [comment]
Just copy the syphon.framework to your xcode project and it should work, you also need to add the suggested path

build settings add ../../../addons/ofxSyphon/libs/Syphon/lib/osx to the Framework Search Paths

**Comment by bangnoise** [comment]
This OpenFrameworks issue is fixed as of OF 0.10.0 RC4
