### ISSUE TITLE
Does not work with multiple windows, GLFW

### ISSUE THREAD

**Issue by prismspecs** [astellato/ofxSyphon#41]
Seems that when I don't use GLUT (can't use glut when creating multiple windows in OF) the syphon stream breaks down and renders a strange result. [See this forum post for images](https://forum.openframeworks.cc/t/is-it-possible-to-create-multiple-windows-with-glut/29189/5?u=aaa).

**Comment by bangnoise** [comment]
Can you provide a minimal example project which recreates the issue?

**Comment by bangnoise** [comment]
Closing this for lack of feedback. Please re-open with the requested project if you'd like anyone to take a look at it.
