### ISSUE TITLE
Is it possible to send through ethernet?

### ISSUE THREAD

**Issue by luisArandas** [astellato/ofxSyphon#46]
Hello, not really sure if this is an issue.

I'm grabbing perfectly the Syphon stream in other apps in the same computer, but I would like to do so with multiple computers using this library. Do I need to make some special bridge to connect this between 2 computers (in the same network) using an ethernet cable/router?

Thanks

**Comment by bangnoise** [comment]
Syphon works between applications on the same computer. You will have to use some other technology to share video between different machines. NDI is a common choice for that these days.
