### ISSUE TITLE
Sharing GL_RGB16 or GL_RGB32F Texture

### ISSUE THREAD

**Issue by m9dfukc** [astellato/ofxSyphon#51]
Hi,

I am trying to share a (pointcloud) texture of ofFloatImage/ofShortImage. But no matter what I try it looks I am loosing data at the receiving end (as if the RGB are only of 8bit per channel).

Is it possible to share a texture that is not of type GL_RGB/GL_RGBA but of type GL_RGB16/GL_RGB32F after all?

**Comment by bangnoise** [comment]
RGBA8 only I'm afraid. This is a limitation of Syphon at the moment. We'd like to add support for other formats at some point.

**Comment by m9dfukc** [comment]
oh no, good to know. I was already getting crazy because it didn't work as expected. I know this does not really belong here but I might ask anyway ... this should ultimately be ported to a PC with ofxSpout (instead of ofxSyphon) do you happen to know if Spout has the same limitation?

**Comment by m9dfukc** [comment]
I gonna close this. Seems to be a limitation of Syphon itself.
