### ISSUE TITLE
Consider removing example project files 

### ISSUE THREAD

**Issue by danomatika** [astellato/ofxSyphon#54]
As oF and Xcode change over time, it is extra maintenance work to manually update the Xcode projects. I'd suggest considering removing all project files which users can generate themselves using the oF ProjectGenerator.

I have done this many years ago with my addons and it hasn't been a major issue since I also include information on how to generate them, ex. https://github.com/danomatika/ofxLua#running-the-example-projects

For this addon, I think the only thing you would need to leave for each example is `addons.make` and `src` with maybe a `bin/data/.gitkeep` thrown in for completeness if/when someone uses the example as a template.

**Comment by bangnoise** [comment]
I think occasionally having to update them is worth it - better than putting new users off with added complexity. A lot of people won't read READMEs.

Also, as OF has added an App Store scheme to generated Xcode projects, it lets us disable that as Syphon does not work in the App Sandbox.

**Comment by danomatika** [comment]
I disagree from experience not having issues with students or beginners using my addons, but if you're cool with the maintenance, it's your project! :)

**Comment by bangnoise** [comment]
I think the second reason (preventing people trying App Store builds) means we need them for this project. It's anyone's project though, thanks for the input!

**Comment by danomatika** [comment]
Also, my perspective is from cross-platform addons where it's simply unmaintainable for one person to re-up the project files for every example project on multiple platforms...as I did *before* the project generator.

In this case, it's one platform and the Xcode projects are relatively stable.
