### ISSUE TITLE
Wishlist - Vector of ofxSyphonClient

### ISSUE THREAD

**Issue by dimitre** [astellato/ofxSyphon#9]
it would be great to be able to use a vector or a map of ofxSyphonClient or servers

```
vector<ofxSyphonClient> syphonClientVec;
```

Cheers!

**Comment by mrbichel** [comment]
I am having issues trying to add ofxSyphonClient to a vector. 
```
vector<ofxSyphonClient *> clients; and vector<ofxSyphonClient> clients;
```
 these either crash my program giving bac access errors inside the name bound client or if it occasionally run they all show the same syphon input.

If I declare them one by one then I don't have any issues. 
```
ofxSyphonClient client1;
ofxSyphonClient client2;
ofxSyphonClient client3;
...
```

**Comment by mrbichel** [comment]
Nevermind. Turns out the issue was I was doing client.setup() after setting name and server, this needs to go before.

**Comment by bangnoise** [comment]
c739fea5b070d0bbdb7900b9200949d4dcd64e00 adds copy and assignment operators for ofxSyphonClient, which permit it to be added to a vector. Open this ticket again if you run into any issues.

**Comment by dimitre** [comment]
great @bangnoise !
